server:
  port: 8080
spring:
  application:
    name: consumer

feign:
  plus:
    connect-timeout: 11000
    max-idle-connections: 520
    read-timeout: 12000
    keep-alive-duration: 30
    write-timeout: 12000
demo:
  url: http://127.0.0.1
  port: 8092

logging:
  level:
    top:
      ming: debug

#management:
#  endpoints:
#    web:
#      exposure:
#        include: 'prometheus'
#  endpoint:
#    metrics:
#      enabled: true
#    prometheus:
#      enabled: true
#    health:
#      show-details: always
#  metrics:
#    export:
#      prometheus:
#        enabled: true
#    tags:
#      application: actuator-demo
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    distribution:
      percentiles:
        all: 0.5,0.75,0.95,0.99
    export:
      prometheus:
        enabled: true
        step: 1m


